add tag: v1.0.5

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -34,10 +34,77 @@ jobs:
             echo "Release $tag created."
           fi
   
+  
+  build_cc_server_and_connctor:
+    runs-on: windows-latest
+    needs: release
+    strategy:
+      matrix:
+        target:
+          - x86_64-pc-windows-msvc
+        #   - i686-pc-windows-msvc
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Rust target
+        run: rustup target add ${{ matrix.target }}
+
+      - name: Download Npcap SDK
+        shell: powershell
+        run: |
+          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
+          Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "$env:USERPROFILE\\npcap-sdk-1.15"
+
+      - name: Set environment for Npcap
+        shell: powershell
+        run: |
+          $NpcapPath = "$env:USERPROFILE\\npcap-sdk-1.15"
+          echo "INCLUDE=$NpcapPath\\Include" | Out-File -Append $env:GITHUB_ENV
+          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
+            echo "LIB=$NpcapPath\\Lib" | Out-File -Append $env:GITHUB_ENV
+          } else {
+            echo "LIB=$NpcapPath\\Lib\\x64" | Out-File -Append $env:GITHUB_ENV
+          }
+
+      - name: Build cici-server
+        shell: powershell
+        env:
+          TARGET: ${{ matrix.target }}
+        run: |
+          $ARTIFACT_NAME = "cici-server"
+          cd apps-rust/$ARTIFACT_NAME
+          cargo build --target $env:TARGET --release
+          cd ../../
+          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+          if (!(Test-Path $BUILT_PATH)) {
+            Write-Error "Build output not found at $BUILT_PATH"
+            exit 1
+          }
+          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}.exe"
+          Copy-Item $BUILT_PATH $OUTPUT_NAME
+          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
+
+      - name: Build cc-connector-android
+        shell: powershell
+        env:
+          TARGET: ${{ matrix.target }}
+        run: |
+          $ARTIFACT_NAME = "cc-connector-android"
+          cd apps-rust/$ARTIFACT_NAME
+          cargo build --target $env:TARGET --release
+          cd ../../
+          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+          if (!(Test-Path $BUILT_PATH)) {
+            Write-Error "Build output not found at $BUILT_PATH"
+            exit 1
+          }
+          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}.exe"
+          Copy-Item $BUILT_PATH $OUTPUT_NAME
+          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
   build_cc_agent_rust:
     name: Build cc-agent-rust
     runs-on: ubuntu-latest
-    needs: release
+    needs: build_cc_server_and_connctor
     strategy:
       matrix:
         target:
@@ -112,73 +179,6 @@ jobs:
         run: |
           TARGET_NAME=$(echo "${{ matrix.target }}" | sed 's/-.*//' | sed 's/armv7a/armv7a/')
           cp target/${{ matrix.target }}/release/cc-agent-rust "assets/cc-agent-rust-${TARGET_NAME}-v${{ env.VERSION }}"
-
-  build_cc_server_and_connctor:
-    runs-on: windows-latest
-    needs: build_cc_agent_rust
-    strategy:
-      matrix:
-        target:
-          - x86_64-pc-windows-msvc
-        #   - i686-pc-windows-msvc
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Install Rust target
-        run: rustup target add ${{ matrix.target }}
-
-      - name: Download Npcap SDK
-        shell: powershell
-        run: |
-          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
-          Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "$env:USERPROFILE\\npcap-sdk-1.15"
-
-      - name: Set environment for Npcap
-        shell: powershell
-        run: |
-          $NpcapPath = "$env:USERPROFILE\\npcap-sdk-1.15"
-          echo "INCLUDE=$NpcapPath\\Include" | Out-File -Append $env:GITHUB_ENV
-          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
-            echo "LIB=$NpcapPath\\Lib" | Out-File -Append $env:GITHUB_ENV
-          } else {
-            echo "LIB=$NpcapPath\\Lib\\x64" | Out-File -Append $env:GITHUB_ENV
-          }
-
-      - name: Build cici-server
-        shell: powershell
-        env:
-          TARGET: ${{ matrix.target }}
-        run: |
-          $ARTIFACT_NAME = "cici-server"
-          cd apps-rust/$ARTIFACT_NAME
-          cargo build --target $env:TARGET --release
-          cd ../../
-          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
-          if (!(Test-Path $BUILT_PATH)) {
-            Write-Error "Build output not found at $BUILT_PATH"
-            exit 1
-          }
-          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}.exe"
-          Copy-Item $BUILT_PATH $OUTPUT_NAME
-          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
-
-      - name: Build cc-connector-android
-        shell: powershell
-        env:
-          TARGET: ${{ matrix.target }}
-        run: |
-          $ARTIFACT_NAME = "cc-connector-android"
-          cd apps-rust/$ARTIFACT_NAME
-          cargo build --target $env:TARGET --release
-          cd ../../
-          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
-          if (!(Test-Path $BUILT_PATH)) {
-            Write-Error "Build output not found at $BUILT_PATH"
-            exit 1
-          }
-          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}.exe"
-          Copy-Item $BUILT_PATH $OUTPUT_NAME
-          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
 
   build_apk:
     name: Build APK
