add tag: v1.0.22

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -7,7 +7,7 @@ on:
 
 env:
   VERSION_NODE: 20.11.1
-  VERSION: 1.0.21
+  VERSION: 1.0.22
   VERSION_ANDROID_NDK: 27.2.12479018
   GH_TOKEN: ${{ github.token }}
 
@@ -35,83 +35,83 @@ jobs:
             echo "Release $tag created."
           fi
   
-#   build_server_client:
-#     runs-on: windows-latest
-#     needs: release
-#     strategy:
-#       matrix:
-#         target:
-#         #   - x86_64-pc-windows-msvc
-#           - i686-pc-windows-msvc
-#     steps:
-#       - uses: actions/checkout@v4
+  build_server_client:
+    runs-on: windows-latest
+    needs: release
+    strategy:
+      matrix:
+        target:
+          - x86_64-pc-windows-msvc
+        #   - i686-pc-windows-msvc
+    steps:
+      - uses: actions/checkout@v4
 
-#       - name: Install Rust target
-#         run: rustup target add ${{ matrix.target }}
+      - name: Install Rust target
+        run: rustup target add ${{ matrix.target }}
 
-#       - name: Download Npcap SDK
-#         shell: powershell
-#         run: |
-#           Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
-#           Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "$env:USERPROFILE\\npcap-sdk-1.15"
+      - name: Download Npcap SDK
+        shell: powershell
+        run: |
+          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
+          Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "$env:USERPROFILE\\npcap-sdk-1.15"
 
-#       - name: Set environment for Npcap
-#         shell: powershell
-#         run: |
-#           $NpcapPath = "$env:USERPROFILE\\npcap-sdk-1.15"
-#           echo "INCLUDE=$NpcapPath\\Include" | Out-File -Append $env:GITHUB_ENV
-#           if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
-#             echo "LIB=$NpcapPath\\Lib" | Out-File -Append $env:GITHUB_ENV
-#           } else {
-#             echo "LIB=$NpcapPath\\Lib\\x64" | Out-File -Append $env:GITHUB_ENV
-#           }
+      - name: Set environment for Npcap
+        shell: powershell
+        run: |
+          $NpcapPath = "$env:USERPROFILE\\npcap-sdk-1.15"
+          echo "INCLUDE=$NpcapPath\\Include" | Out-File -Append $env:GITHUB_ENV
+          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
+            echo "LIB=$NpcapPath\\Lib" | Out-File -Append $env:GITHUB_ENV
+          } else {
+            echo "LIB=$NpcapPath\\Lib\\x64" | Out-File -Append $env:GITHUB_ENV
+          }
 
-#       - name: Build cici-server
-#         shell: powershell
-#         env:
-#           TARGET: ${{ matrix.target }}
-#         run: |
-#           $ARTIFACT_NAME = "cici-server"
-#           cd apps-rust/$ARTIFACT_NAME
-#           cargo build --target $env:TARGET --release
-#           cd ../../
-#           $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
-#           if (!(Test-Path $BUILT_PATH)) {
-#             Write-Error "Build output not found at $BUILT_PATH"
-#             exit 1
-#           }
-#           if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
-#               $TARGET_NAME = "i686"
-#           } else {
-#               $TARGET_NAME = "x86_64"
-#           }
-#           $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}-win32-$TARGET_NAME.exe"
-#           Copy-Item $BUILT_PATH $OUTPUT_NAME
-#           gh release upload ${{ github.ref_name }} $OUTPUT_NAME
+      - name: Build cici-server
+        shell: powershell
+        env:
+          TARGET: ${{ matrix.target }}
+        run: |
+          $ARTIFACT_NAME = "cici-server"
+          cd apps-rust/$ARTIFACT_NAME
+          cargo build --target $env:TARGET --release
+          cd ../../
+          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+          if (!(Test-Path $BUILT_PATH)) {
+            Write-Error "Build output not found at $BUILT_PATH"
+            exit 1
+          }
+          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
+              $TARGET_NAME = "i686"
+          } else {
+              $TARGET_NAME = "x86_64"
+          }
+          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}-win32-$TARGET_NAME.exe"
+          Copy-Item $BUILT_PATH $OUTPUT_NAME
+          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
 
-#       - name: Build cc-connector-android
-#         shell: powershell
-#         env:
-#           TARGET: ${{ matrix.target }}
-#         run: |
-#           $ARTIFACT_NAME = "cc-connector-android"
-#           cd apps-rust/$ARTIFACT_NAME
-#           cargo build --target $env:TARGET --release
-#           cd ../../
-#           $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
-#           if (!(Test-Path $BUILT_PATH)) {
-#             Write-Error "Build output not found at $BUILT_PATH"
-#             exit 1
-#           }
+      - name: Build cc-connector-android
+        shell: powershell
+        env:
+          TARGET: ${{ matrix.target }}
+        run: |
+          $ARTIFACT_NAME = "cc-connector-android"
+          cd apps-rust/$ARTIFACT_NAME
+          cargo build --target $env:TARGET --release
+          cd ../../
+          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+          if (!(Test-Path $BUILT_PATH)) {
+            Write-Error "Build output not found at $BUILT_PATH"
+            exit 1
+          }
 
-#           if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
-#               $TARGET_NAME = "i686"
-#           } else {
-#               $TARGET_NAME = "x86_64"
-#           }
-#           $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}-win32-$TARGET_NAME.exe"
-#           Copy-Item $BUILT_PATH $OUTPUT_NAME
-#           gh release upload ${{ github.ref_name }} $OUTPUT_NAME
+          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
+              $TARGET_NAME = "i686"
+          } else {
+              $TARGET_NAME = "x86_64"
+          }
+          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}-win32-$TARGET_NAME.exe"
+          Copy-Item $BUILT_PATH $OUTPUT_NAME
+          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
 
   build_cc_agent_rust:
     name: Build cc-agent-rust
@@ -120,9 +120,9 @@ jobs:
     strategy:
       matrix:
         target:
-          - armv7-linux-androideabi
-        #   - aarch64-linux-android
-        #   - x86_64-linux-android
+        #   - armv7-linux-androideabi
+          - aarch64-linux-android
+          - x86_64-linux-android
     env:
       CARGO_TERM_COLOR: always
     steps:
@@ -173,7 +173,7 @@ jobs:
             armv7-linux-androideabi)
               cp $TOOLCHAIN/armv7a-linux-androideabi$API-clang $TOOLCHAIN/armv7-linux-androideabi$API-clang
               echo "CC_armv7a_linux_androideabi=$TOOLCHAIN/armv7a-linux-androideabi$API-clang" >> $GITHUB_ENV
-              echo "CC_armv7_linux_androideabi=$TOOLCHAIN/armv7a-linux-androideabi$API-clang" >> $GITHUB_ENV
+              echo "CC_armv7_linux_androideabi=$TOOLCHAIN/armv7-linux-androideabi$API-clang" >> $GITHUB_ENV
               echo "AR_armv7a_linux_androideabi=$TOOLCHAIN/llvm-ar" >> $GITHUB_ENV
               echo "AR_armv7_linux_androideabi=$TOOLCHAIN/llvm-ar" >> $GITHUB_ENV
               ;;
@@ -205,6 +205,7 @@ jobs:
               ;;
           esac
           cp target/${{ matrix.target }}/release/cc-agent-rust target/${{ matrix.target }}/release/cc-agent-rust-v${{ env.VERSION }}-$TARGET_NAME
+          gh release upload ${{ github.ref_name }} target/${{ matrix.target }}/release/cc-agent-rust-v${{ env.VERSION }}-$TARGET_NAME
 
   build_apk:
     name: Build APK
