add tag: v1.0.14

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -7,7 +7,7 @@ on:
 
 env:
   VERSION_NODE: 20.11.1
-  VERSION: 1.0.13
+  VERSION: 1.0.14
   VERSION_ANDROID_NDK: 27.2.12479018
   GH_TOKEN: ${{ github.token }}
 
@@ -35,83 +35,83 @@ jobs:
             echo "Release $tag created."
           fi
   
-  build_server_client:
-    runs-on: windows-latest
-    needs: release
-    strategy:
-      matrix:
-        target:
-        #   - x86_64-pc-windows-msvc
-          - i686-pc-windows-msvc
-    steps:
-      - uses: actions/checkout@v4
+#   build_server_client:
+#     runs-on: windows-latest
+#     needs: release
+#     strategy:
+#       matrix:
+#         target:
+#         #   - x86_64-pc-windows-msvc
+#           - i686-pc-windows-msvc
+#     steps:
+#       - uses: actions/checkout@v4
 
-      - name: Install Rust target
-        run: rustup target add ${{ matrix.target }}
+#       - name: Install Rust target
+#         run: rustup target add ${{ matrix.target }}
 
-      - name: Download Npcap SDK
-        shell: powershell
-        run: |
-          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
-          Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "$env:USERPROFILE\\npcap-sdk-1.15"
+#       - name: Download Npcap SDK
+#         shell: powershell
+#         run: |
+#           Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
+#           Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "$env:USERPROFILE\\npcap-sdk-1.15"
 
-      - name: Set environment for Npcap
-        shell: powershell
-        run: |
-          $NpcapPath = "$env:USERPROFILE\\npcap-sdk-1.15"
-          echo "INCLUDE=$NpcapPath\\Include" | Out-File -Append $env:GITHUB_ENV
-          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
-            echo "LIB=$NpcapPath\\Lib" | Out-File -Append $env:GITHUB_ENV
-          } else {
-            echo "LIB=$NpcapPath\\Lib\\x64" | Out-File -Append $env:GITHUB_ENV
-          }
+#       - name: Set environment for Npcap
+#         shell: powershell
+#         run: |
+#           $NpcapPath = "$env:USERPROFILE\\npcap-sdk-1.15"
+#           echo "INCLUDE=$NpcapPath\\Include" | Out-File -Append $env:GITHUB_ENV
+#           if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
+#             echo "LIB=$NpcapPath\\Lib" | Out-File -Append $env:GITHUB_ENV
+#           } else {
+#             echo "LIB=$NpcapPath\\Lib\\x64" | Out-File -Append $env:GITHUB_ENV
+#           }
 
-      - name: Build cici-server
-        shell: powershell
-        env:
-          TARGET: ${{ matrix.target }}
-        run: |
-          $ARTIFACT_NAME = "cici-server"
-          cd apps-rust/$ARTIFACT_NAME
-          cargo build --target $env:TARGET --release
-          cd ../../
-          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
-          if (!(Test-Path $BUILT_PATH)) {
-            Write-Error "Build output not found at $BUILT_PATH"
-            exit 1
-          }
-          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-win32-v${{ env.VERSION }}.exe"
-          Copy-Item $BUILT_PATH $OUTPUT_NAME
-          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
+#       - name: Build cici-server
+#         shell: powershell
+#         env:
+#           TARGET: ${{ matrix.target }}
+#         run: |
+#           $ARTIFACT_NAME = "cici-server"
+#           cd apps-rust/$ARTIFACT_NAME
+#           cargo build --target $env:TARGET --release
+#           cd ../../
+#           $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+#           if (!(Test-Path $BUILT_PATH)) {
+#             Write-Error "Build output not found at $BUILT_PATH"
+#             exit 1
+#           }
+#           $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-win32-v${{ env.VERSION }}.exe"
+#           Copy-Item $BUILT_PATH $OUTPUT_NAME
+#           gh release upload ${{ github.ref_name }} $OUTPUT_NAME
 
-      - name: Build cc-connector-android
-        shell: powershell
-        env:
-          TARGET: ${{ matrix.target }}
-        run: |
-          $ARTIFACT_NAME = "cc-connector-android"
-          cd apps-rust/$ARTIFACT_NAME
-          cargo build --target $env:TARGET --release
-          cd ../../
-          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
-          if (!(Test-Path $BUILT_PATH)) {
-            Write-Error "Build output not found at $BUILT_PATH"
-            exit 1
-          }
-          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-win32-v${{ env.VERSION }}.exe"
-          Copy-Item $BUILT_PATH $OUTPUT_NAME
-          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
+#       - name: Build cc-connector-android
+#         shell: powershell
+#         env:
+#           TARGET: ${{ matrix.target }}
+#         run: |
+#           $ARTIFACT_NAME = "cc-connector-android"
+#           cd apps-rust/$ARTIFACT_NAME
+#           cargo build --target $env:TARGET --release
+#           cd ../../
+#           $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+#           if (!(Test-Path $BUILT_PATH)) {
+#             Write-Error "Build output not found at $BUILT_PATH"
+#             exit 1
+#           }
+#           $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-win32-v${{ env.VERSION }}.exe"
+#           Copy-Item $BUILT_PATH $OUTPUT_NAME
+#           gh release upload ${{ github.ref_name }} $OUTPUT_NAME
 
   build_cc_agent_rust:
     name: Build cc-agent-rust
     runs-on: ubuntu-latest
-    needs: build_server_client
+    needs: release
     strategy:
       matrix:
         target:
         #   - armv7a-linux-androideabi
           - aarch64-linux-android
-        #   - x86_64-linux-android
+          - x86_64-linux-android
     env:
       CARGO_TERM_COLOR: always
     steps:
@@ -286,63 +286,63 @@ jobs:
           gh release upload ${{ github.ref_name }} \
              "${{ env.MAKE_OUT_DIR }}/squirrel.windows/x64/${{ env.PROJECT_NAME }}-win32-x64-${{ env.VERSION }} Setup.exe"
 
-  build_mac_server_client:
-    name: build_mac_server_client for macOS
-    runs-on: macos-latest
-    needs: release
-    strategy:
-      matrix:
-        target:
-          - x86_64-apple-darwin
-          - aarch64-apple-darwin
-    steps:
-      - uses: actions/checkout@v4
+#   build_mac_server_client:
+#     name: build_mac_server_client for macOS
+#     runs-on: macos-latest
+#     needs: release
+#     strategy:
+#       matrix:
+#         target:
+#           - x86_64-apple-darwin
+#           - aarch64-apple-darwin
+#     steps:
+#       - uses: actions/checkout@v4
 
-      - name: Install Rust target
-        run: rustup target add ${{ matrix.target }}
+#       - name: Install Rust target
+#         run: rustup target add ${{ matrix.target }}
 
-      - name: Build cici-server
-        run: |
-          ARTIFACT_NAME=cici-server
-          cd apps-rust/$ARTIFACT_NAME
-          cargo build --target ${{ matrix.target }} --release
-          cd ../../
-          BUILT_PATH=target/${{ matrix.target }}/release/$ARTIFACT_NAME
+#       - name: Build cici-server
+#         run: |
+#           ARTIFACT_NAME=cici-server
+#           cd apps-rust/$ARTIFACT_NAME
+#           cargo build --target ${{ matrix.target }} --release
+#           cd ../../
+#           BUILT_PATH=target/${{ matrix.target }}/release/$ARTIFACT_NAME
           
-          PLATFORM=$(echo ${{ matrix.target }} | sed 's/.*-//')
+#           PLATFORM=$(echo ${{ matrix.target }} | sed 's/.*-//')
 
-          case "${{ matrix.target }}" in
-            x86_64-apple-darwin)
-              TARGET_NAME=x86_64
-              ;;
-            aarch64-apple-darwin)
-              TARGET_NAME=arm64
-              ;;
-          esac
-          echo $TARGET_NAME
-          OUTPUT_NAME=target/${{ matrix.target }}/release/$ARTIFACT_NAME-$PLATFORM-$TARGET_NAME-v${{ env.VERSION }}
-          cp "$BUILT_PATH" "$OUTPUT_NAME"
-          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
+#           case "${{ matrix.target }}" in
+#             x86_64-apple-darwin)
+#               TARGET_NAME=x86_64
+#               ;;
+#             aarch64-apple-darwin)
+#               TARGET_NAME=arm64
+#               ;;
+#           esac
+#           echo $TARGET_NAME
+#           OUTPUT_NAME=target/${{ matrix.target }}/release/$ARTIFACT_NAME-$PLATFORM-$TARGET_NAME-v${{ env.VERSION }}
+#           cp "$BUILT_PATH" "$OUTPUT_NAME"
+#           gh release upload ${{ github.ref_name }} $OUTPUT_NAME
 
-      - name: Build cc-connector-android
-        run: |
-          ARTIFACT_NAME=cc-connector-android
-          cd apps-rust/$ARTIFACT_NAME
-          cargo build --target ${{ matrix.target }} --release
-          cd ../../
-          BUILT_PATH=target/${{ matrix.target }}/release/$ARTIFACT_NAME
-          PLATFORM=$(echo ${{ matrix.target }} | sed 's/.*-//')
+#       - name: Build cc-connector-android
+#         run: |
+#           ARTIFACT_NAME=cc-connector-android
+#           cd apps-rust/$ARTIFACT_NAME
+#           cargo build --target ${{ matrix.target }} --release
+#           cd ../../
+#           BUILT_PATH=target/${{ matrix.target }}/release/$ARTIFACT_NAME
+#           PLATFORM=$(echo ${{ matrix.target }} | sed 's/.*-//')
 
-          case "${{ matrix.target }}" in
-            x86_64-apple-darwin)
-              TARGET_NAME=x86_64
-              ;;
-            aarch64-apple-darwin)
-              TARGET_NAME=arm64
-              ;;
-          esac
-          echo $TARGET_NAME
-          OUTPUT_NAME=target/${{ matrix.target }}/release/$ARTIFACT_NAME-$PLATFORM-$TARGET_NAME-v${{ env.VERSION }}
-          cp "$BUILT_PATH" "$OUTPUT_NAME"
-          gh release upload ${{ github.ref_name }} $OUTPUT_NAME
+#           case "${{ matrix.target }}" in
+#             x86_64-apple-darwin)
+#               TARGET_NAME=x86_64
+#               ;;
+#             aarch64-apple-darwin)
+#               TARGET_NAME=arm64
+#               ;;
+#           esac
+#           echo $TARGET_NAME
+#           OUTPUT_NAME=target/${{ matrix.target }}/release/$ARTIFACT_NAME-$PLATFORM-$TARGET_NAME-v${{ env.VERSION }}
+#           cp "$BUILT_PATH" "$OUTPUT_NAME"
+#           gh release upload ${{ github.ref_name }} $OUTPUT_NAME
 
