ci

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -9,6 +9,9 @@ env:
 permissions:
     contents: write
 
+
+env:
+  VERSION: 1.0.1
 jobs:
     desktop-build:
         name: desktop-build
@@ -22,8 +25,6 @@ jobs:
                       dist: /apps/desktop/out/make/squirrel.windows/x64/*Setup.exe
         runs-on: ${{ matrix.os }}
         timeout-minutes: 30
-        env:
-            VERSION: 1.0.53
             PROJECT_NAME: CiCy
             GITHUB_REPOSITORY: ${{ github.repository }}
             MAKE_OUT_DIR: ${{ github.workspace }}/apps/desktop/out/make
@@ -65,7 +66,7 @@ jobs:
   build_apk:
     name: Build APK
     runs-on: ubuntu-latest
-    needs: release
+    needs: build_cc_server_and_connctor
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -121,6 +122,93 @@ jobs:
           mv ./apps/cc-agent-adr/app/build/outputs/apk/debug/app-debug.apk ./apps/cc-agent-adr/app/build/outputs/apk/debug/app-${{env.VERSION}}.apk
           gh release upload ${{ github.ref_name }} ./apps/cc-agent-adr/app/build/outputs/apk/debug/app-${{env.VERSION}}.apk
 
+  build_cc_server_and_connctor:
+    runs-on: windows-latest
+    needs: release
+    strategy:
+      matrix:
+        target:
+          - x86_64-pc-windows-msvc
+          - i686-pc-windows-msvc
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Rust target
+        run: rustup target add ${{ matrix.target }}
+
+      - name: Download Npcap SDK
+        shell: powershell
+        run: |
+          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
+          Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "$env:USERPROFILE\\npcap-sdk-1.15"
+      - name: Set environment for Npcap
+        shell: powershell
+        run: |
+          $NpcapPath = "$env:USERPROFILE\\npcap-sdk-1.15"
+          echo "INCLUDE=$NpcapPath\\Include" | Out-File -Append $env:GITHUB_ENV
+
+          if ($env:TARGET -eq "i686-pc-windows-msvc") {
+            echo "LIB=$NpcapPath\\Lib" | Out-File -Append $env:GITHUB_ENV
+          } else ($env:TARGET -eq "x86_64-pc-windows-msvc") {
+            echo "LIB=$NpcapPath\\Lib\\x64" | Out-File -Append $env:GITHUB_ENV
+          }
+          
+      - name: Build cici-server
+        shell: powershell
+        env:
+          TARGET: ${{ matrix.target }}
+        run: |
+          mkdir assets
+          $ARTIFACT_NAME = "cici-server"
+          Set-Location "apps-rust/$ARTIFACT_NAME"
+          cargo build --target $env:TARGET --release
+          cd ../../
+          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+          if (!(Test-Path $BUILT_PATH)) {
+            Write-Error "Build output not found at $BUILT_PATH"
+            exit 1
+          }
+
+          if ($env:TARGET -eq "i686-pc-windows-msvc") {
+            $TARGET_NAME = "i686"
+          } else ($env:TARGET -eq "x86_64-pc-windows-msvc") {
+            $TARGET_NAME = "x86_64"
+          }
+          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{evn.VERSION}}.exe"
+          echo $OUTPUT_NAME
+          Copy-Item $BUILT_PATH $OUTPUT_NAME
+          gh release upload $OUTPUT_NAME
+
+          
+      - name: Build cc-connector-android
+        shell: powershell
+        env:
+          TARGET: ${{ matrix.target }}
+        run: |
+          mkdir assets
+          $ARTIFACT_NAME = "cc-connector-android"
+          Set-Location "apps-rust/$ARTIFACT_NAME"
+          cargo build --target $env:TARGET --release
+          $VERSION = (Select-String -Path Cargo.toml -Pattern '^version =' | Select-Object -First 1).Line -replace '.*version = "(.*)".*','$1'
+          Write-Host "Version: $VERSION"
+          cd ../../
+          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
+          if (!(Test-Path $BUILT_PATH)) {
+            Write-Error "Build output not found at $BUILT_PATH"
+            exit 1
+          }
+
+          if ($env:TARGET -eq "i686-pc-windows-msvc") {
+            $TARGET_NAME = "i686"
+          } if ($env:TARGET -eq "x86_64-pc-windows-msvc") {
+            $TARGET_NAME = "x86_64"
+          } 
+
+          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{evn.VERSION}}.exe"
+          echo $OUTPUT_NAME
+          Copy-Item $BUILT_PATH $OUTPUT_NAME
+          gh release upload $OUTPUT_NAME
+          
     release:
         name: Release pushed tag
         runs-on: ubuntu-22.04
